export const ImagesPath={
    lock: require('../../Assets/Images/Lock.png'),
    arrow:require('../../Assets/Images/Arrow.png'),
    AuthenticImage:require('../../Assets/Images/AuthenticScreen.png'),
    User:require('../../Assets/Images/User.png'),
    lockicon:require('../../Assets/Images/lockicon.png'),
    eyeicon:require('../../Assets/Images/eyeicon.png'),
    eyeSlashicon: require('../../Assets/Images/eyeSlashicon.png'),
    googleicon:require('../../Assets/Images/google.png'),
    appleicon:require('../../Assets/Images/apple.png'),
    facebookicon:require("../../Assets/Images/facebook.png"),
    Emailicon:require("../../Assets/Images/Emailicon.png"),
    HomeIcon:require("../../Assets/Images/home.png"),
    FavouriteIcon:require("../../Assets/Images/Favourite.png"),
    FilterIcon:require("../../Assets/Images/filtericon.png"),
    CartIcon:require("../../Assets/Images/cart.png"),
    ProfileIcon:require("../../Assets/Images/ProfileIcon.png"),
    Cameraicon: require("../../Assets/Images/Cameraicon.png"),
    FilterIconhome:require("../../Assets/Images/FilterIconhome.png"),
    EllipseIcon:require("../../Assets/Images/ellipseIcon.png"),
    Clock:require("../../Assets/Images/clock.png"),
    Star:require("../../Assets/Images/star.png"),
    leftArrow:require("../../Assets/Images/leftArrow.png"),
    Share:require("../../Assets/Images/share.png"),
    RatingStar:require("../../Assets/Images/RatingStar.png"),
    UnfillRatingStar:require("../../Assets/Images/UnfillRatingStar.png"),
    ProfilePic:require("../../Assets/Images/ProfilePic.png")
}